### ISSUE TITLE
Missing numpy include directory

### ISSUE THREAD

**Issue by bs610** [dfujim/mudpy#3]
On my machine, I get an error when trying to pip install the package, as clang cannot find `numpy/arrayobject.h` when building the mud_friendly extension.

This can be fixed by adding numpy to the list of `include_dirs` in setup.py:

```
include_dirs=[numpy.get_include(), './mud_src/'])
```

**Comment by dfujim** [comment]
Apparently I fixed this in commit 8841caea51ce848101a1b853ff85e3055b82da08, but I forgot to push it. Sorry about that!
