### ISSUE TITLE
Build failure in Python 3.12

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/mudpy#8]
Attempting a fresh install (e.g., using `pip3 install --user mud-py`) with Python 3.12 yields the following output & error message:

<pre>Collecting mud-py
  Using cached mud-py-1.2.14.tar.gz (246 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  <font color="#C01C28"><b>error</b></font>: <b>subprocess-exited-with-error</b>
  
  <font color="#C01C28">×</font> <font color="#26A269">Getting requirements to build wheel</font> did not run successfully.
  <font color="#C01C28">│</font> exit code: <font color="#2AA1B3"><b>1</b></font>
  <font color="#C01C28">╰─&gt;</font> <font color="#C01C28">[33 lines of output]</font>
  <font color="#C01C28">   </font> Traceback (most recent call last):
  <font color="#C01C28">   </font>   File &quot;/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py&quot;, line 353, in &lt;module&gt;
  <font color="#C01C28">   </font>     main()
  <font color="#C01C28">   </font>   File &quot;/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py&quot;, line 335, in main
  <font color="#C01C28">   </font>     json_out[&apos;return_val&apos;] = hook(**hook_input[&apos;kwargs&apos;])
  <font color="#C01C28">   </font>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  <font color="#C01C28">   </font>   File &quot;/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py&quot;, line 112, in get_requires_for_build_wheel
  <font color="#C01C28">   </font>     backend = _build_backend()
  <font color="#C01C28">   </font>               ^^^^^^^^^^^^^^^^
  <font color="#C01C28">   </font>   File &quot;/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py&quot;, line 77, in _build_backend
  <font color="#C01C28">   </font>     obj = import_module(mod_path)
  <font color="#C01C28">   </font>           ^^^^^^^^^^^^^^^^^^^^^^^
  <font color="#C01C28">   </font>   File &quot;/usr/lib64/python3.12/importlib/__init__.py&quot;, line 90, in import_module
  <font color="#C01C28">   </font>     return _bootstrap._gcd_import(name[level:], package, level)
  <font color="#C01C28">   </font>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1387, in _gcd_import
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1310, in _find_and_load_unlocked
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 488, in _call_with_frames_removed
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1387, in _gcd_import
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1331, in _find_and_load_unlocked
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 935, in _load_unlocked
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 994, in exec_module
  <font color="#C01C28">   </font>   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 488, in _call_with_frames_removed
  <font color="#C01C28">   </font>   File &quot;/tmp/pip-build-env-58jhuh5a/overlay/lib/python3.12/site-packages/setuptools/__init__.py&quot;, line 16, in &lt;module&gt;
  <font color="#C01C28">   </font>     import setuptools.version
  <font color="#C01C28">   </font>   File &quot;/tmp/pip-build-env-58jhuh5a/overlay/lib/python3.12/site-packages/setuptools/version.py&quot;, line 1, in &lt;module&gt;
  <font color="#C01C28">   </font>     import pkg_resources
  <font color="#C01C28">   </font>   File &quot;/tmp/pip-build-env-58jhuh5a/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py&quot;, line 2172, in &lt;module&gt;
  <font color="#C01C28">   </font>     register_finder(pkgutil.ImpImporter, find_on_path)
  <font color="#C01C28">   </font>                     ^^^^^^^^^^^^^^^^^^^
  <font color="#C01C28">   </font> AttributeError: module &apos;pkgutil&apos; has no attribute &apos;ImpImporter&apos;. Did you mean: &apos;zipimporter&apos;?
  <font color="#C01C28">   </font> <font color="#C01C28">[end of output]</font>
  
  <font color="#A347BA"><b>note</b></font>: This error originates from a subprocess, and is likely not a problem with pip.
<font color="#C01C28"><b>error</b></font>: <b>subprocess-exited-with-error</b>

<font color="#C01C28">×</font> <font color="#26A269">Getting requirements to build wheel</font> did not run successfully.
<font color="#C01C28">│</font> exit code: <font color="#2AA1B3"><b>1</b></font>
<font color="#C01C28">╰─&gt;</font> See above for output.

<font color="#A347BA"><b>note</b></font>: This error originates from a subprocess, and is likely not a problem with pip.
</pre>

The `AttributeError` reflects the [removal of several (previously deprecated) modules in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html#importlib).

Though much has been [written about this change](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean?noredirect=1&lq=1), a remedy for building `mudpy` is unclear to me...

**Comment by dfujim** [comment]
The issue seems to be more related to setuptools than pip. Recently pip has been moving away from setuptools as an installation backend, but it still seems like the [best (only?)](https://docs.cython.org/en/stable/src/userguide/source_files_and_compilation.html) way of compiling cython code with pip. I take it that the "install setuptools for python3.12" didn't work? Something like `python3.12 -m pip install setuptools`

**Comment by dfujim** [comment]
resolved in 06944bd3c86002f521e85ca456f42ed01afa0b7d by updating to meson-python build backend
